#! /bin/bash

export VERSION="38"
export SYSTEM_DESC="ChimeraOS Holo"
export SYSTEM_NAME="chimeraos-holo"
export USERNAME="gamer"
export SIZE="15000MB"
export ARCHIVE_DATE=""
export WEBSITE="https://github.com/ruineka/chimeraos"
export DOCUMENTATION_URL="https://github.com/ruineka/chimeraos"
export BUG_REPORT_URL="https://github.com/ruineka/chimeraos/issues"

export KERNEL_PACKAGE="linux"

export PACKAGES="\
	plasma \
	plasma-wayland-session \
	kde-applications \
	gnome-control-center \
	fuse2 \
	amd-ucode \
	intel-ucode \
	htop \
	sddm \
	accountsservice \
	xorg-server \
	bluez \
	bluez-utils \
	bluez-plugins \
	bluez-hid2hci \
	lib32-freetype2 \
	lib32-curl \
	lib32-libgpg-error \
	networkmanager \
	lib32-libnm \
	pipewire \
	lib32-pipewire \
	pipewire-alsa \
	pipewire-pulse \
	pipewire-jack \
	wireplumber \
	gst-plugin-pipewire \
	xdg-desktop-portal \
	xdg-desktop-portal-wlr \
	alsa-utils \
	alsa-firmware \
	sof-firmware \
	alsa-ucm-conf \
	sudo \
	python \
	flatpak \
	vulkan-icd-loader \
	lib32-vulkan-icd-loader \
	mesa-demos \
	libva-vdpau-driver \
	lib32-libva-vdpau-driver \
	xf86-video-amdgpu \
	libva-intel-driver \
	lib32-libva-intel-driver \
	intel-media-driver \
	dkms \
	nvidia-dkms \
	nvidia-utils \
	lib32-nvidia-utils \
	nvidia-prime \
	ttf-liberation \
	wqy-zenhei \
	openssh \
	diffutils \
	logrotate \
	unzip \
	which \
	linux-firmware \
	nss-mdns \
	haveged \
	pulsemixer \
	usbutils \
	ethtool \
	nano \
	gamemode \
	lib32-gamemode \
	podman \
	lshw \
	rsync \
	dosbox \
	broadcom-wl-dkms \
	intel-undervolt \
	cifs-utils \
	nfs-utils \
	smbclient \
	usb_modeswitch \
	sxhkd \
	fmt \
	openal \
	lib32-openal \
	wavpack \
	libcurl-gnutls \
	libidn11 \
	liquidctl \
	dmidecode \
	iio-sensor-proxy \
	steam \
"

export AUR_PACKAGES="\
	frzr \
	python-vdf \
	python-inotify-simple \
	alienware-alpha-wmi \
	wyvern \
	gamescope \
	gamescope-session-git \
	r8152-dkms \
	r8168-dkms \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	oxp-platform-dkms-git \
	xone-dkms \
	xpad-noone-dkms \
	xpadneo-dkms \
	bcm20702a1-firmware \
	nintendo-udev \
	steam-removable-media-git \
	handygccs-git \
	hhfc-git \
	legendary \
	boxtron \
	ryzenadj-git \
	rtl88x2bu-dkms-git \
	rtw89-dkms-git \
"

export SERVICES="\
	frzr-autoupdate.timer \
	NetworkManager \
	sddm \
	bluetooth \
	bluetooth-workaround \
	fstrim.timer \
	avahi-daemon \
	haveged \
	systemd-timesyncd \
	sshd \
	handycon \
"

export USER_SERVICES="\
	gamemoded.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/boot/syslinux \
"

postinstallhook() {

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

}
